x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "100m"

services:
  db:
    image: postgres:16.2
    env_file: judge0.conf
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    restart: always
    logging: *default-logging

  redis:
    image: redis:7.2.4
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly no --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: judge0.conf
    ports:
      - "6380:6379"
    restart: always
    logging: *default-logging

  server:
    image: judge0/judge0:latest
    ports:
      - "2358:2358"
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    env_file: judge0.conf
    privileged: true
    depends_on:
      - db
      - redis
    restart: always
    logging: *default-logging

  worker:
    image: judge0/judge0:latest
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    env_file: judge0.conf
    privileged: true
    depends_on:
      - db
      - redis
    restart: always
    logging: *default-logging

volumes:
  postgres-data:
